### ISSUE TITLE
javaday2017

### ISSUE THREAD

**Issue by aliaksei-lithium** [JavaBy/jprof-hugo#16]
Как чёткие партнёры для javaday2017, надо подготовить посты в fb/vk/сайт/рассылка. 

**fb/vk**

Приглашаем на конференцию JavaDay 2017 в Минске 3 июня! В программе доклады и мастер-классы от супер-звёзд индустрии: Егора Бугаенко, Philipp Krenn, Александра Тарасова и многих других! Отдавая должное популярности Java, на конференции речь пойдёт не только о ней, но и о практиках, инструментах, подходах и даже философии. Spring Boot, JWT, мониторинг контейнеров, правильная интеграция между микросервисами, Continuous Delivery – всё то, без чего Java Enterprise не может существовать в 2017 году. Билеты и детали – на http://javaday.by/. #javadayby

**рассылка**

3 июня пройдет 6-я международная конференция JavaDay Minsk 2017!

В программе доклады про микросервисы, Spring Boot, контейнеры, DevOps, Scala, Kotlin, Go...

Подтвержденные спикеры и доклады:
1. Yegor Bugayenko – Object Oriented JUnit Tests
Второй год подряд на JavaDay Minsk будет выступать Егор Бугаенко, многим известный за свой нестандартный подход к разработке и понимаю ООП. В этот раз он затронет тему юнит тестирования, расскажет, как писать юнит тесты в ООП стиле, и как ООП поможет повысить такие качества кода как поддерживаемость, читаемость и расширяемость.

2. Andrey Ershov – Evolution of Future in Java&Scala
Сегодня асинхронное программирование становится все более востребованным. В своем докладе Андрей расскажет об эволюции базового примитива асинхронной разработки - Future, а также сравнит реализацию CompletableFuture в Java 8 с реализацией в Scala.

3. Philipp Krenn – Monitor Your Containers
Сегодня уже не нужно объяснять необходимость контейнеризации, ее плюсы и минусы. Но с началом использования контейнеров возникает вопрос их мониторинга. Philipp в своем докладе расскажет, как настроить мониторинг контейнеров с использованием Elastic стека, а также покажет, как это работает в демо.

4. David Pilato – Advanced Search For Your Legacy Application
David покажет, как интегрировать ElasticSearch с легаси приложением, написанным со стандартным стеком джава разработчика: RestX+ Hibernate + Postgres/MySQL.

5. Aleksandr Tarasov – Service Discovery: More Than Seems
Микросервисы, распределенные системы. Задачу конфигурации и service discovery решают множество продуктов: Netflix Eureka, Consul, etcd или даже старый добрый Zookeeper. Но главный вопрос не то, какой инстанс можно вызывать, а то, какой лучше вызвать. Александр Тарасов расскажет о проекте Spring Cloud, о том, как он позволяет интегрировать выше перечисленные продукты и решает типичные проблемы.

6. Hrvoje Crnjak – Session is dead – Long live JWT
Session. Сколько сложностей в такой простой вещи: привязка, кеши, репликация, хранение. Одим словом – стейтфул. Что же такое JWT и как он поможет вам избавится от всего этого груза, расскажет Hrvoje Crnjak в своем докладе Session is dead - Long live JWT.

7. Кирилл Толкачев – Проклятие Spring Boot Test
Вместе с Кириллом Толкачевым попробуем разобраться в деталях того, какие грабли нам аккуратно подложили тут и там. Для этого протестируем «типичное» приложение и зададим себе вопросы, которые должен задавать любой разработчик, использующий Spring и яростно внедряющий Spring Boot на своих проектах.

8. Michael Hüttermann – From Zero to Hero: Firing up a holistic Continuous Delivery/DevOps pipeline
Что нам стоит Continuos Delivery Pipeline построить: Jenkins 2, SonarQube, Docker, Artifactory, Bintray и ELK. Соединим все это в один пайплайн вместе с Michael Hüttermann.

И это еще не все! После конференции, конечно же, все приглашаются на афтерпати.

Регистрация и продажа билетов – https://bezkassira.by/javaday_2017-2538/. #javadayby

**Comment by IRus** [comment]
Промокод: JPROFBY_JAVADAY_15
+ один билет на розыгрыш
