### ISSUE TITLE
Рефакторинг пермалинков

### ISSUE THREAD

**Issue by IRus** [JavaBy/jprof-hugo#8]
Текущие ссылки ужасны:

http://jprof.by/post/170204-001/

Пропозал: сделать темплейт для ссылок вот таким:

http://jprof.by/post/category-date-name-of-event-or-what-ever

http://jprof.by/post/anons-meetup-1
http://jprof.by/post/anons-meetup-2
http://jprof.by/post/anons-meetup-3

http://jprof.by/post/otchet-meetup-1
http://jprof.by/post/otchet-meetup-2
http://jprof.by/post/otchet-meetup-3

http://jprof.by/post/partner-2016-01-31-jetconf
http://jprof.by/post/partner-2016-02-31-bkug
http://jprof.by/post/partner-2016-03-31-united-dev-conf

Пример: https://github.com/Heapy/bjug.by/tree/master/content/blog

Сейчас это выглядит так: 

https://github.com/JavaBy/jprof-hugo/tree/master/content/post

Пример еще одного успешного применения:

https://github.com/JavaBy/jprof-hugo/tree/master/static/img

Пример еще одного пиздеца:

https://github.com/JavaBy/jprof-hugo/tree/master/static/img/post

Плюсы:

- из название файла понятно что будет внутри
- есть удобная навигация по типам (групировка по типам в файл менеджере)

Минусы:

- нету сортировки по датам 

Для меня нету критичности сортировки по датам, и я не вижу юзкейсов где она действительна must-have

TODO:

- [ ] Определиться с форматом
- [ ] Процесс миграции делать с редиректами - старые ссылки должны продолжать работать

**Comment by IRus** [comment]
Приглашаю всех активных участников сообщества проголосовать за пост, и выразить обоснованную критику. 

@JavaBy/community-leaders

**Comment by bsiamionau** [comment]
> Богдан, [06.02.17 12:28]
я частично согласен, что урл выглядит поганенько

> Богдан, [06.02.17 12:29]
можно переделать с http://jprof.by/post/170204-001/

> Богдан, [06.02.17 12:29]
на, например

> Богдан, [06.02.17 12:29]
http://jprof.by/post/2017-02-04-meetup-13-anons/

Это решает проблему с тем, что непонятно, что внутри.
Мне не нравится идея с темплейтом имени ссылок. Это работает пока ты один работаешь над постами. Если их пишет несколько человек - формат дата-описание поста всегда 100% согласованное между всеми. А твой вариант требует конвенции (анонсы мы начинаем с такого префикса, а партнерски посты - с такого, а такие-то посты - с третьего) - что усложняет процесс поиска постов на фс многократно.

**Comment by IRus** [comment]
> А твой вариант требует конвенции (анонсы мы начинаем с такого префикса, а партнерски посты - с такого, а такие-то посты - с третьего) - что усложняет процесс поиска постов на фс многократно.

Это никак не усложняет, а только упрощает процесс, т.к. посты сгрупированы по типу, что отвечает паттерну созданию новых постов:

Нужно создать новый анонс - вот группа анонсов, бери последний анонс. 
Нужно создать рекламый пост - вот они, группой расположены.

В случае с датами нужно сканить весь диапазон в поиске поста, и дата тут никак не помогает (особенно если ты не знаешь когда был написан пост).

**Comment by bsiamionau** [comment]
ты не понимаешь проблемы.

если тебе надо написать пост, который не подпадает под классические паттерны, то ты получаешь имя, которое известно только тебе. второй человек сможет найти его только просмотрев все файлы в директории. если они отсортированы по дате добавления - это делать гораздо проще

**Comment by IRus** [comment]
> ты не понимаешь проблемы.

я отлично понимаю проблему, потому что я работал над сайтом несколько часов в это воскреснье и сполна насладился "удобством" текущего именования.

>  пост, который не подпадает под классические паттерны, то ты получаешь имя, которое известно только тебе.

и оно будет лежать сильно отдельно от остальных, т.к. остальные будут расположены по группам. пока у нас нету никаких предпосылок, чтобы будут такие посты. И даже если будут, они еще больше усложнят поиск постов в основных категориях: анонсы, отчеты, партнерыю

**Comment by bsiamionau** [comment]
> я отлично понимаю проблему, потому что я работал над сайтом несколько часов в это воскреснье и сполна насладился "удобством" текущего именования.

любопытно, чем ты занимался? потому что при составлении новых постов даже текущее именование (без текстового пояснения) удобно.

> (пост с уникальных именен) будет лежать сильно отдельно от остальных

если тебе не хватает группировки - есть еще один вариант.

    /group_date_comment

например

    /partners-2017-02-06-bkug-meetup

главное - чтобы была хронология внутри группы.

**Comment by aliaksei-lithium** [comment]
Совместим время и тип. Дата удобна, но не понятно о чём пост. Плюс не забывать удобство редактирования прямо с гитхаба(как я делаю). Однако, можно делать посты только c дамами, т.е. паттерн применим к стандартным постам.
Группировка – много постов будет не так удобно, согласен, но пока это не проблема же... Однако, мы можем попробовать для одной группы делать группировку, например для анонсов митапов
`/meetup/02-02-2017-jprof13.md`

**Comment by IRus** [comment]
> любопытно, чем ты занимался? потому что при составлении новых постов даже текущее именование (без текстового пояснения) удобно.

я обновлял все посты с фотками: отчеты, для этого мне пришлось открывать все файлы, в случае с твоим подходом я так же бегал по всем файлам, т.к. нету групировки.

> /partners-2017-02-06-bkug-meetup

уже лучше, для отчетов и митапо дата правда полностью лишняя

т.е. предлагаю делать так: не использовать для митапов и отчетов дату, номер - основная информация, дата итак несоклько рах дублируется в посте

Пример:

partners-2017-02-06-bkug-meetup
partners-2017-02-06-jet-conf

но

meetup-1
meetup-2
meetup-otchet-1
meetuo-otchet-2
coffee-code-1
coffee-code-2
coffee-code-otchet-1
coffee-code-otchet-2

**Comment by bsiamionau** [comment]
> Пример:
> 
> partners-2017-02-06-bkug-meetup
> partners-2017-02-06-jet-conf
> 
> но
> 
> meetup-1
> meetup-2
> meetup-otchet-1
> meetuo-otchet-2
> coffee-code-1
> coffee-code-2
> coffee-code-otchet-1
> coffee-code-otchet-2
> 
> при этом хронология внутри группы соблюдается

имеет смысл

**Comment by IRus** [comment]
обновил пропозал

**Comment by IRus** [comment]
One-liner to add alias to posts :)

```
for file in *.md; do echo -e "aliases = [\"/post/${file%.*}\"]\n$(cat $file)" > $file; done
```
