### ISSUE TITLE
Images issue

### ISSUE THREAD

**Issue by IRus** [JavaBy/jprof-hugo#9]
Сейчас все картинки хранятся в гит, идея с git lfs провалилась по следующим причинам:
- github имеет месячный лимит 1гб на LFS -> можем выйти за лимиты
- нужна установка каждому редактору
- если git lfs не установлен, можно спокойно запушить картинку как есть

Решение:

Перейти на S3(или любой другой аналог): написать скрипты для отправки/скачки картинкок.

Предлагаю проголосовать( :+1:  :-1:  ) или обсудить данную инициативу.

@JavaBy/community-leaders

**Comment by madhead** [comment]
Может, Jprof'овский Google Drive? Да, он жмёт качество, но фотки не учитываются в лимитах по размеру. Можно шарить сразу альбомами.

**Comment by IRus** [comment]
А как шарить альбомом на сайт:

**Comment by aliaksei-lithium** [comment]
И всё же предлагаю сделать наше хранилище на S3 или Google cloud storage. Я вот даже за второй вариант. Одна проблема – на кого акк, но могу взять на себя. Шарить креды только по запросу пару человекам. Может на будущее заодно и понадобиться какой нибудь сервис сделать.

**Comment by IRus** [comment]
Если что, у меня есть свой акк на aws

**Comment by aliaksei-lithium** [comment]
Ну тогда я предлагаю тебе заняться этим, и подумать потом, что бы дать ограниченный доступ на бакет некоторым людям по awscli. По деньгам выйдет не много – но решим этот вопрос, ок?

**Comment by IRus** [comment]
Окей, могу тогда предложить маленький jar, который будет сканить папку, заливать diff на s3, а на выходе давать готовую разметку для статей

**Comment by alzhyn** [comment]
Ок, отлично! Т.е. работа с фотками такая,
1. [Опционально] Скачать бакет и контент
2. добавить в папку новый контент(удалить старый)
3. Залить diff в бакет

**Comment by aliaksei-lithium** [comment]
Ок, отлично! Т.е. работа с фотками такая,
1. [Опционально] Скачать бакет и контент
2. добавить в папку новый контент(удалить старый)
3. Залить diff в бакет
4. Получить список файлов(и паблик линки на них) без скачивания

**Comment by IRus** [comment]
Ну да, у тебя есть локальная папка, и ты посути делаешь rsync в aws. А на выходе у тебя текстовый файлик с сгрупированным по "папкам" ссылкам с разметкой под наши требования.

**Comment by madhead** [comment]
>А как шарить альбомом на сайт?

Вставить линку на альбом и всё? На отдельные фотки - пермалинки.

**Comment by madhead** [comment]
Шарить альбомы GDrive нельзя, закрыли тему.

Картинки по-прежнему заливаются в репу, так и в лимит (100 Mb) недолго. Может, Imgur, лол?

**Comment by aliaksei-lithium** [comment]
S3 походу хороший варик

**Comment by IRus** [comment]
@madhead @aliaksei-lithium https://github.com/IRus/FS2S3

**Comment by madhead** [comment]
@IRus, https://rclone.org/ ?

**Comment by IRus** [comment]
Ну или так

**Comment by madhead** [comment]
Походу, неактуально. Закрою, чтобы не висело.
